# Q3
USE information_schema;
SELECT COLUMN_NAME, i.TABLE_NAME FROM TABLE_CONSTRAINTS i
LEFT JOIN KEY_COLUMN_USAGE k ON i.CONSTRAINT_NAME = k.CONSTRAINT_NAME
WHERE k.CONSTRAINT_SCHEMA = 'Chinook' AND i.CONSTRAINT_TYPE = 'FOREIGN KEY' AND  i.TABLE_SCHEMA = 'Chinook';
